### ISSUE TITLE
Apologies for posting here, but...

### ISSUE THREAD

**Issue by Craigson** [mvolkmann/mvolkmann.github.com#2]
Hi Mark,

Apologies for creating an issue, but I couldn't find any contact info for you. Did you ever find a solution  to your Appcenter issue posted here: https://github.com/Microsoft/appcenter/issues/224

Thanks,
Craig

**Comment by mvolkmann** [comment]
Unfortunately no. I’ve given up on using Appcenter for now.

**Comment by Craigson** [comment]
Well that's disconcerting, thanks for responding!
